# Generated by Django 5.1.6 on 2025-03-02 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filme',
            old_name='criado_em',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='filme',
            name='imdb_id',
        ),
        migrations.AlterField(
            model_name='filme',
            name='ano',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='filme',
            name='genero',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
